name: Assign Issues on Comment

on:
  issue_comment:
    types: [created]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Assign the issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking the comment for assignment commands"
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} > issue.json

          COMMENT_BODY="${{ github.event.comment.body }}"
          COMMENT_AUTHOR="${{ github.event.comment.user.login }}"
          ISSUE_ASSIGNEES=$(jq -r '.assignees | map(.login) | join(",")' issue.json)

          if [[ "$COMMENT_BODY" =~ ^(take|assign me)$ ]]; then
            echo "Assigning issue to $COMMENT_AUTHOR"
            curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{"assignees":["'"$COMMENT_AUTHOR"'"]}' \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          else
            echo "No action required for comment: $COMMENT_BODY"
          fi

